### ISSUE TITLE
Convert sifz to sif

### ISSUE THREAD

**Issue by reSHARMA** [synfig/synfig-tests-regressions#24] opened 2018-11-21 09:59 UTC
Include complex examples from https://github.com/synfig/synfig/tree/master/synfig-core/examples

They are saved as "sifz" files, so the task would be to re-save them all to "sif". Possibly, through a script which turns all sifz files to sif.

**Comment by morevnaproject** [comment] 2018-11-21 15:51
I have changed label for this issue, since "sifz" is just a gzipped "sif" file. ^__^

**Comment by reSHARMA** [comment] 2018-11-23 14:26
This issue was moved to NJACKWinterOfCode/synfig-tests-regressions#11

**Comment by morevnaproject** [comment] 2018-12-13 07:38
Closed by https://github.com/NJACKWinterOfCode/synfig-tests-regressions/pull/15

**Closed as completed by morevnaproject** 2018-12-13 07:38 UTC
Labels: Intermediate
